# Generated by Django 4.2.4 on 2023-08-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=40)),
                ('dni', models.CharField(max_length=8, verbose_name='D.N.I')),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('vive', models.BooleanField(default=True)),
                ('fecha_nac', models.DateField(verbose_name='Fecha nacimiento')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
