# Generated by Django 4.2.4 on 2023-08-29 21:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='legajo',
            field=ckeditor.fields.RichTextField(default='legajo'),
        ),
    ]
